name: flutter_notes_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  sqlbrite: ^2.2.0
  provider: ^6.0.2
  equatable: ^2.0.3
  auto_route: ^3.2.2
  hive_flutter: ^1.1.0
  google_fonts: ^2.3.1
  synchronized: ^3.0.0
  moor_flutter: ^4.0.0
  path_provider: ^2.0.8
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.1
  hive: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  moor_generator: ^4.6.0+1
  auto_route_generator: ^3.2.1

flutter:
  uses-material-design: true